database:
  username: sa
  password:
  name: testdb
  mode: mem

spring:
  application:
    name: beanified-app
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
